### ISSUE TITLE
MeetUp // Köln // @grandcentrix

### ISSUE THREAD

**Issue by midnightrun** [gocologne/meetups#11]
Hi,
ich würde gern das nächste MeetUp in Köln starten. Irgendwelche Termine die besonders gut passen, habt ihr Talks oder Session vorschläge. Immer her damit :)

August/September sollten wir etwas finden :) 

Chéers!

**Comment by as27** [comment]
Da wir ja mitten in der Urlaubszeit sind, wäre so ein kleiner Hacking Event vielleicht cool. 

Ansonsten würde ich gerne auch mal eine Session mit Concurrency Patterns machen. Ziel wäre es unterschiedliche Patterns einfach mal zu sammeln.

Eine andere Möglichkeit wäre einfach einen coolen Talk anzusehen und danach darüber zu sprechen. In Frankfurt wollen die gemeinsam folgenden Talk ansehen:
Steve Francia - Go: building on the shoulders of giants and stepping on a few toes

Terminlich ist das bei mir im ganzen August gut.

**Comment by midnightrun** [comment]
So,
bin zurück von der GopherConUk. Viele haben von Liz Rice - Container from Scratch gesprochen. Könnte man sich auch ansehen. Ich stelle schon mal einen Termin rein, passt für dich der 22.8 @as27 ?

**Comment by BusyBeeSI** [comment]
sehr cool, evtl könntest du auch einfach von der Con was erzählen und ein paar Bilder zeigen. Wäre bestimmt spannend :)

**Comment by as27** [comment]
@midnightrun ja Infos von der GopherCon das wäre cool. Hast Du vielleicht Sticker übrig?

**Comment by BusyBeeSI** [comment]
@midnightrun Gab es da auch Gopher Stofftiere? :D

**Comment by midnightrun** [comment]
Ich habe ein paar Sticker auf jeden Fall und kann gerne über die Conf. generell sprechen, den Talks die ich gesehen habe :)
