### ISSUE TITLE
Vorschlag für Meeting am 22.08.2018 bei grandcentrix in Köln

### ISSUE THREAD

**Issue by headcr4sh** [gocologne/meetups#12]
Ich kann ein paar Worte zu Terraform (https://terraform.io/, Tool zum Verwalten von [Cloud-]Infrastruktur als Code) verlieren und darauf eingehen, wie sich Terraform durch eigene Provider Plugins erweitern lässt.

Terraform Provider Plugins werden in Go geschrieben und der Einstieg in deren Entwicklung ist dank einer wirklich gut dokumentierten API recht einfach.

Ich kann anhand eines selbst entwickelten Plugins zeigen, was hier möglich ist und wie Go beim Thema "Infrastructure-as-Code" einsetzbar ist.

**Comment by JohannesKaufmann** [comment]
Vielleicht auch noch mal kurz auf [Pulumi](https://www.pulumi.com/) eingehen. Wurde vor kurzem veröffentlicht und ich finde es recht spannend, würde aber gerne mal von anderen mit mehr Erfahrung hören was sie davon halten.

**Comment by BusyBeeSI** [comment]
Mich würde interessieren: 

- Buffalo.io
- Cobra/Viper
- Hugo 
- MongoDB with Go

**Comment by midnightrun** [comment]
@headcr4sh das hört sich super an und würde ich als Thema eintragen. @JohannesKaufmann @BusyBeeSI könnt ihr etwas zu den vorgeschlagenen Themen sagen oder suchen wir Leute mit Erfahrung? Dann könnten wir es nachden Lightning Talk(s) ansprechen :)

**Comment by BusyBeeSI** [comment]
ich hab leider keine Erfahrung damit, bin noch ein freshman was go angeht :)

**Comment by midnightrun** [comment]
@BusyBeeSI dann bist du genau richtig bei uns. Willkommen und wir können die Themen direkt anfragen ;)

**Comment by BusyBeeSI** [comment]
vielen Dank :)

**Comment by JohannesKaufmann** [comment]
@midnightrun Ich könnte einen Vortrag über Crawling mit [goquery](https://github.com/PuerkitoBio/goquery) machen. Dabei könnte ich an realen Beispielen anschaulich die go Basics erklären (maps, struct, parse numbers, ...). Allerdings würde ich concurrency herauslassen. Zum Beispiel:
1. Seite laden -> http.Get
2. Titel aus [blog post](https://www.grandcentrix.net/2017/06/08/news/featured/homekit-ios-11-viele-neue-moglichkeiten-fur-automation-und-kein-apple-auth-chip-mehr/) rausholen. -> find element, extract text, print value
3. Meta Daten extrahieren (Autor, Datum, …) -> struct
4. [Liste](https://www.grandcentrix.net/news/) von Blog Posts extrahieren -> goquery ForEach & arrays
5. Derzeitige Seite in der Pagination herausfinden -> parse number
6. …

Nur zur Warnung: Ich fange erst nächsten Monat mit dem Studium an (habe also noch keine professionelle Erfahrung) und habe bis jetzt noch nie einen Vortrag bei einem Meetup gehalten. Dafür nutze ich golang bereits seit einem Dreivierteljahr sehr ausführlich, um verschiedene crawler zu schreiben (zum Beispiel um Daten von Steam zu bekommen, die nicht durch die Api erhältlich sind).

Wenn ihr noch Ideen habt, welche Website(n) interessant sind und welche golang basics man erklärt könnte wäre ich sehr dankbar dafür.

---

Zu terraform kann ich leider nichts sagen, da ich da keine Erfahrung habe.

**Comment by JohannesKaufmann** [comment]
@midnightrun Ich komme leider erst am Abend mit dem Zug zurück, ich kann also leider doch nicht kommen. Tut mir echt leid.

**Comment by midnightrun** [comment]
Schade @JohannesKaufmann Vlt. dann einfach nächstes mal :)

**Comment by midnightrun** [comment]
Okay, ich werde eine Mob Programming Session anbieten. Wer noch nicht weiß was dies ist, sollte einfach teilnehmen :)
