### ISSUE TITLE
Golang Meetup @ gcx 12.02

### ISSUE THREAD

**Issue by sleeping-barber** [gocologne/meetups#16]
Hi,
Termin steht so gut wie fest. Hat jemand eine Session der er gerne machen würde?

**Comment by sleeping-barber** [comment]
Dependency Injection werde ich als Session machen 💯

**Comment by as27** [comment]
Ja ich kann wieder eine machen, aber nur wenn @midnightrun mir die Unterlagen zu DI schickt ;-) 

Die Themen, welche in den letzten Workshops immer wieder nachgefragt wurden: Webdesing und "wie mit Go Anfangen?". Daraus hätte ich drei Session Themen:

* Ein Filespliter mit Go (CLI, io.Reader, io.Writer, Tests)
* Ein einfacher Webserver mit Go (Server, Router, REST API und Template)
* Templates für Hugo (Go Templates extreme)

Ich finde alle drei Themen spannend und in der Zeit machbar (Ein Thema pro Abend). Aber aktuell kann ich mich nicht entscheiden.

**Comment by sleeping-barber** [comment]
DI Slides kann ich dir dann schicken, wobei ich es Hands On gestalten möchte.
