### ISSUE TITLE
Meetup @gcx, 25. September

### ISSUE THREAD

**Issue by sleeping-barber** [gocologne/meetups#17]
Ahoy ⚓️
Wie ihr wisst, findet das Meetup am Mittwoch statt. Gibt es irgendwelche Themen, Workshops die jemand präsentieren möchte?

Cheers!

**Comment by sleeping-barber** [comment]
Netzwerkprogrammierung in Go könnte ich bspw. anbieten.

**Comment by alex77g** [comment]
ich fänds cool, wenn wir mal ne session mit grpc machen würden. Ich hab im Urlaub mal angefangen ein Microservice Stack aufzubauen und habe da bis jetzt mehr Fragen als Antworten gefunden :smile:

**Comment by sleeping-barber** [comment]
Ich könnte tatsächlich eine Session gRPC anbieten falls Interesse besteht. Du kannst gern deine Frage hier posten und ich schaue ob ich diese beantworten könnte :)

**Comment by as27** [comment]
Ich gehe gerade die [Release Notes von 1.13](https://golang.org/doc/go1.13) durch.  Das wäre eigentlich so ein Thema, wo man gemeinsam als Warm-Up reden könnte. 

* Erweiterung der Literale
* die Umstellung auf Module und Proxy Server
* Anpassung von go get
* errors.Wrap()
* ...

Da ist dieses mal schon einiges dabei.

Thematisch könnte man auch über den [GopherCon Talk über Generics](https://www.youtube.com/watch?v=WzgLqE-3IhY) reden. Obwohl ich das Thema nicht mag, finde ich die Argumentation wirklich gut.

**Comment by sleeping-barber** [comment]
Ggf. kann meine eine Session machen wo man vorab mit allen den Talk schaut und dann darüber diskutiert?

**Comment by alex77g** [comment]
> Ich könnte tatsächlich eine Session gRPC anbieten falls Interesse besteht. Du kannst gern deine Frage hier posten und ich schaue ob ich diese beantworten könnte :)

das ist nett. Vielen Dank. ich weiss nicht wie ich komplexere struct slices am besten per gRPC versende. Bis jetzt habe ich nur unary grpcs verwendet, aber das ist glaube ich der falsche weg oder?

**Comment by sleeping-barber** [comment]
Hi Alex,
so wie ich das verstehe willst du eine komplexere Datenstruktur versenden. Da spielt die `Service Method` keine Rolle. Die ist dafür da bspw. eine Verbindung aufzubauen die in beide Richtungen (Client/Server) streamen kann ... sehr cooles Feature.

Ggf. hilft dir das Keyword `repeated` bereits weiter? https://grpc.io/docs/guides/concepts/#repeated

Hiermit wird deine definierte Message zu einem Slice :) 

```go
   1   │ syntax = "proto3";
   2   │ package golang;
   3   │
   4   │ message Todos {
   5   │   repeated Todo todos = 1;
   6   │ }
   7   │
   8   │ message Todo {
   9   │   int32 id = 1;
  10   │   string name = 2;
  11   │   bool done = 3;
  12   │ }
```

Wird generiert zu:

```go
   1   │ // Code generated by protoc-gen-go. DO NOT EDIT.
   2   │ // source: type.proto
   3   │
   4   │ package golang
   5   │
   6   │ import proto "github.com/golang/protobuf/proto"
   7   │ import fmt "fmt"
   8   │ import math "math"
   9   │
  10   │ // Reference imports to suppress errors if they are not otherwise used.
  11   │ var _ = proto.Marshal
  12   │ var _ = fmt.Errorf
  13   │ var _ = math.Inf
  14   │
  15   │ // This is a compile-time assertion to ensure that this generated file
  16   │ // is compatible with the proto package it is being compiled against.
  17   │ // A compilation error at this line likely means your copy of the
  18   │ // proto package needs to be updated.
  19   │ const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package
  20   │
  21   │ type Todos struct {
  22   │     Todos                []*Todo  `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
  23   │     XXX_NoUnkeyedLiteral struct{} `json:"-"`
  24   │     XXX_unrecognized     []byte   `json:"-"`
  25   │     XXX_sizecache        int32    `json:"-"`
  26   │ }
```

Hilft das weiter?

**Comment by alex77g** [comment]
Hi Camal, danke für die schnelle Antwort.
meine Frage war nicht gut formuliert. Solange ich kein Struct im Struct habe, bekomme ich das hin.
Wie kann ich folgenden Aufbau übertragen?

```
type address struct {
	street string
	city string
	country string
} 

type user struct {
	name string
	login string
	passwd string
	age int
	addresses []address
} 
```
Ich glaub mit repeated alleine komm ich hier nicht weiter oder?
