### ISSUE TITLE
Go Code verstehen bevor man welchen schreibt

### ISSUE THREAD

**Issue by midnightrun** [gocologne/meetups#3]
Hi,
ich würde gern den Punkt aufgreifen von Bill Kennedy im GoTime Podcast: https://changelog.com/gotime/72

Er empfiehlt Leuten erst einmal Go Code zu verstehen, bevor man welchen schreibt. Ich würde gemeinsam mit der Gruppe (Anfängern und Erfahrenen) das kleine Tool https://github.com/tj/node-prune ansehen und zusammen erarbeiten, was das Tool tut und wie dies implementiert worden ist.

Chéers!

**Comment by as27** [comment]
Die Idee ist super, das Paket ist relativ schlecht dokumentiert: https://godoc.org/github.com/tj/node-prune
Der Umfang ist jedoch übersichtlich und das sind auf den ersten Blick spannende Sachen dabei.

**Comment by midnightrun** [comment]
Done. Hat Spaß gemacht.
