### ISSUE TITLE
StriveCDN wie und warum wir Go nutzen

### ISSUE THREAD

**Issue by chrisprobst** [gocologne/meetups#4]
StriveCDN ist ein auf Go basierendes P2P-Hybrid CDN für Live Streaming.
In einem bel. langen/kurzen Talk könnte ich ein paar technische Hürden und die allgemeine Infrastruktur beleuchten, die wir bei StriveCDN nutzen.
Dazu gerne ein paar kniffligere Themen wie Concurrency und Management von vielen Goroutinen.

**Comment by midnightrun** [comment]
@chrisprobst spannendes Thema! @as27 kriegen wir das im nächsten MeetUp unter als Lightning Talk und danach springen wir in die Sessions?

Vielen Danke @chrisprobst für das Angebot 👍

**Comment by chrisprobst** [comment]
Sry die meetup seite hatte nicht richtig geladen ich hatte „teilnehmen“ im Sinn. Ich bin gerade in NYC und fliege gleich nach Deutschland, gerne in beiden Formaten, erst Lightening Talk und später wenn mehr Zeit ist nochmal ausführlich. Brauche nur feedback damit ich vorher was vorbereiten kann.

**Comment by as27** [comment]
Also ok. Dann freuen wir uns. 
Inhaltlich sollte der Lightening Talk auch für Anfänger interessant sein. Also nicht zu viel Code ;-)
 
Den Talk würde ich gleich nach der Begrüßung und noch vor den Pizzas ansetzen. Kurz nach 19 Uhr. Ist das in Ordnung?

**Comment by chrisprobst** [comment]
Klasse, super. Wie lang etwa?

**Comment by as27** [comment]
Also vom Bauch her würde ich sagen: alles zwischen 5 und 15 Minuten ist super.

**Comment by midnightrun** [comment]
Extrem cooler Talk. Ggf. nächstes mal ein Follow-up (deep dive in die Implementierung?)

**Comment by as27** [comment]
Auch nochmal Danke für den Talk, war echt super.
