### ISSUE TITLE
Go für die Webentwicklung

### ISSUE THREAD

**Issue by ajfriesen** [gocologne/meetups#6]
Ich würde mich gerne etwas näher mit Webentwicklung beschäftigen.

Vielleicht hat ja jemand Erfahrung und kann etwas erzählen.
* Welche Webframeworks gibt es?
* Wann sollte und sollte man diese nicht nutzen?
* Welche guten Quellen gibt es für Webentwicklung in Go?

**Comment by as27** [comment]
Ja hier, insbesondere mit gobufallo hab ich Erfahrung. Hab da letztes Jahr ein paar große Pull Requests gemacht.
@ajfriesen ganz guter Vorschlag, ich denke auch dass wir hierzu was machen sollten.

**Comment by fvosberg** [comment]
Das wird eine rege Diskussion, weil mir persönlich gobuffalo unsypathisch ist. Was definierst Du denn als Webentwicklung @ajfriesen? REST-Server? HTML-Seiten? Webassembly? Bei REST gibt es einige, die sich an der Diskussion gut beteiligen können und ich fänd es auch spannend, etwas tieferen Einblick in gobuffalo zu bekommen ohne es benutzen zu müssen 👍

**Comment by ajfriesen** [comment]
@fvosberg Da ich überhaupt keine Erfahrung mit der Webentwicklung habe und auch wenig Programmiererfahrung, kann ich keine Antwort geben.

Persönlich würde mich interessieren, wie man kleine Webapplikationen ohne das Rad andauernd neu erfinden zu müssen schreibt.
Gobuffalo ist mir auch schon über den Weg gelaufen und würde mich sehr interessieren. 

Als Anfänger hat man einfach die Qual der Wahl und ich würde einfach gerne schnell zu Ergebnissen kommen. Es geht für mich ja (noch) nicht um hochskalierbare produktive Umgebungen.

**Comment by as27** [comment]
Das klingt doch schon sehr gut. Also ich persönlich sehe zu dem Thema folgende kleine Lernziele:

* **Verwenden von Go Templates**: Einfach eine kurze Einführung wie Templates verwendet werden können. Das ganze läuft unabhängig von Webseiten und kann auch Beispiele für Code Generierung beinhalten. Ob ich jetzt Go oder HTML Code erzeuge ist ja eigentlich gleich. 
* **Encoding und Decoding**: Wie können Daten ausgetauscht werden? Eine kurze Einführung in JSON und XML Encoding und Decoding. Diese Technik würde ich ja dann anstatt HTML Templates verwenden, wenn ich einen REST Service erstelle.
* **Code Strukturierung für Web Server**: Gliederung des Codes, damit HTML und REST Services sich nicht in die Quere kommen. Wo packe ich meine Business Logik hin?
* **Interfaces für die Verwaltung von Daten**: Damit man unabhängig von der Datenbank ist, wäre eine Entkopplung über ein Interface das Mittel der Wahl. Zusätzlich benötige ich das auch, um meine Business Logik auch ohne Datenbank testen zu können.

@ajfriesen würdest Du Dir hierzu vielleicht sogar ein Thema zutrauen? Ich kann Dich dabei gerne unterstützen. Der Vorteil wenn Du das aufbereitest ist, dass es insbesondere für Anfänger verständlicher wird. Zusätzlich würdest Du dabei am schnellsten lernen.
