### ISSUE TITLE
Meetup Planung Juni 26.06. bei webfactory

### ISSUE THREAD

**Issue by as27** [gocologne/meetups#7]
Ich nimm den Schwung aus dem letzten meetup mit und würde gleich in die Planung des nächsten Treffens übergehen. 

Folgende Punkte brauchen wir, aber am Wichtigsten ist die Location.

* [x] location: dieses mal vielleicht in Bonn?
* [x] sponsor: food und drinks
* [x] sessions
* [x] talks

Das wann kommt dann auch zusammen mit dem wo.

**Comment by xkons** [comment]
@as27 Hi Andreas, die webfactory würde sich freuen den nächsten Golang-Meetup zu hosten!

Unser Veranstaltungsraum ist in der Lessingstraße 63, 53113 Bonn, nicht weit vom Hauptbahnhof und wir würden auch food und drinks sponsern ;)

**Comment by domano** [comment]
@as27 Hey, wir können das auch gerne mal wieder in der tarent machen, auch gern als Ausweichplan falls webfactory doch nicht gehen sollte (war ja schon 2 Mal in der tarent).

Wäre auch Bonn, Rochusstr. 2-4 53123 Bonn.

**Comment by smancke** [comment]
Und natürlich steht auch das neue *snabble*-Büro jederzeit zur Verfügung:
Acherstraße 26-28, 53111 Bonn - direkt in der City.

Bzgl. Terminen sollten wir mal schauen, was so noch in die Sommer-Planung rein passt. Bei uns würde sich die letzte Juli-Woche (23.-27.) anbieten.

**Comment by midnightrun** [comment]
gcx, Köln, würde ggf. letzte Juni Woche passen. Wir bauen gerade die erste Etage aus und haben dann sogar eine dedizierte Community Fläche.

Kann aber noch nichts festmachen, da Juni/Juli total voll sind und einige Konferenzen anstehen (z.b. ElmConf in Paris, eine Frontendsprache die man sich mal sehen sollte :) )

**Comment by as27** [comment]
Super vielen Dank für die schnelle Rückmeldung.
@xkons Webfactory wollten wir ja schon eigentlich früher machen. Wann würde es bei Euch im Juni passen?

Alle anderen Vorschläge sind definitiv nicht aufgehoben.

**Comment by xkons** [comment]
@as27 ich bin da noch recht flexibel, lediglich 20, 21, 28, und 29. Juni wären ungünstig, ansonsten passt jeder Termin im Juni 🙂

**Comment by helvalius** [comment]
@as27 Viaboxx ist bisher noch nicht im Meetup aktiv, wir haben aber auch Entwickler die sich für Go interessieren. Wir sind auch immer gerne ein Host f wie auch bei anderen Meetups wenn ihr mal was sucht. 

Wir sitzen in Niederdollendorf (Hauptstrasse 164, 53639 Königswinter), ganz gut mit der Regionalbahn aus Köln zu erreichen.

**Comment by as27** [comment]
@xkons Terminfindung läuft. 
Damit wir einen monatlichen Rhythmus bekommen würde ich den Termin gerne Ende Juni einplanen:
Mit den bisherigen Einschränkungen hätten wir: 18., 19., 22., 25., 26. oder 27. Juni
@helvalius ich hab viaboxx auch gleich in meine Liste aufgenommen.

**Comment by fvosberg** [comment]
Bei Viaboxx war ich auch schon mal bei einem Meetup, damals hatten sie mit Go noch nichts zu tun, das Haus ist aber sehr cool und man kann Spiele auf Packstationen spielen :rocket:.

**Comment by as27** [comment]
@xkons nach den paar Rückmeldungen würde ich jetzt dann den 26.06. (Dienstag) einplanen. Ist das von Deiner Seite aus in Ordnung?

**Comment by xkons** [comment]
@as27 Dienstag 26.06 passt!

**Comment by as27** [comment]
So meetup ist erstellt. @xkons ist es bei Euch auch möglich, dass wir evtl. wieder kleinere Sessions machen? D.h. wir würden dann zwei bis drei kleine Gruppen machen. Dafür bräuchte man dann aber auch zwei bis drei abgetrennte Räume. Wenn nicht dann machen wir Talks und danach ungezwungenes Hacken.

**Comment by as27** [comment]
Kein Problem, wir sind ja flexibel. 
Das mit der Adresse kann ich irgendwie nicht anpassen. Ich hab das aber als Kommentar schon vermerkt.

**Comment by midnightrun** [comment]
Closed :)
