### ISSUE TITLE
Vorschlag Talk bei webfactory am 26.06.

### ISSUE THREAD

**Issue by chrisprobst** [gocologne/meetups#8]
Hallo Zusammen,

ich würde gerne noch einen Talk machen.

Vorschlag wäre für das Echo Framework plus CockroachDB und pop ORM.

Ich würde eine simple App vorbereiten beim Talk durchzugehen.

Ziel soll sein, eine gute Übersicht über vorhandene WebFrameworks zu haben und speziell Echo+pop anwenden zu können.

**Comment by as27** [comment]
Ja der Vorschlag ist super. Ich setz den Talk gleich auf die Agenda.

**Comment by as27** [comment]
Ich könnte evtl. was über Gobuffalo beitragen. POP und Gobuffalo sind ja beide von Mark Bates.

**Comment by chrisprobst** [comment]
Prima, gerne. Vlt. können wir das sogar teilen. Oder gemeinsam halten. Dafür bräuchten wir dann nur eine sinnvolle Gliederung. Ich hatte bisher noch keine Zeit etwas vorzubereiten. Vlt. schaff ich es Freitag.

**Comment by as27** [comment]
Gerne zusammen.
Ich würde Buffalo nur ganz kurz vorstellen und das anhand von ein wenig Live Coding. 
Zusätzlich würde ich ein wenig auf "Idiomatic Go" eingehen, da Buffalo da nicht ganz so idiomatischen Code erzeugt. Insbesondere Buffalo Context hat mit context.Context nicht so viel zu tun. Das ist ja auch in Ordnung, jedoch sollte man schon unbedingt drauf hinweisen.

**Comment by midnightrun** [comment]
@chrisprobst könntest du ggf. den Source Code für das Beispiel freigeben auf GitHub. Ich würde es mir sehr gern ansehen :) 👍

**Comment by as27** [comment]
Ich mach den Issue mal zu. @chrisprobst das Thema bleibt aber heiß
